name       : gcc
version    : 7.3.0
release    : 38
source     :
    - https://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz : 832ca6ae04636adbb430e865a1451adf6979ab44ca1c8374f61fba65645ce15c
homepage   : http://gcc.gnu.org/
license    :
    - GPL-3.0
component  :
    - system.devel
    - ^g++ : system.devel
    - ^gfortran : system.devel
    - ^gfortran-32bit : emul32
    - ^libgcc : system.base
    - ^libgcc-32bit : emul32
    - ^libstdc++ : system.base
    - ^libstdc++-32bit : emul32
    - ^libgomp : system.base
    - ^libgomp-32bit : emul32
    - ^libgfortran : programming.library
    - ^libgfortran-32bit : emul32
autodep    : no
ccache     : no
summary    : GNU Compiler Collection
description: |
    The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...). GCC was originally written as the compiler for the GNU operating system. The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom.
builddeps  :
    - glibc-32bit-devel
    - isl-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
rundeps    :
    - mpc
    - mpfr
    - ^g++ : gcc
    - ^gfortran :
        - gcc
        - libgfortran
    - ^libgcc-32bit : libgcc
    - ^libstdc++-32bit : libstdc++
    - ^libgomp-32bit :
        - libgcc-32bit
        - libgomp
    - ^libgfortran-32bit : libgfortran
replaces   :
    - ^libgfortran-32bit : gfortran-32bit
patterns   :
    - ^libgcc :
        - /usr/lib64/libgcc*
        - /usr/lib64/libcc1*
        - /usr/lib64/libasan*
        - /usr/lib64/libtsan*
        - /usr/lib64/libatomic*
        - /usr/lib64/libitm*
        - /usr/lib64/libquadmath*
        - /usr/lib64/libssp*
        - /usr/lib64/libmudflap*
        - /usr/lib64/libsanit*
        - /usr/lib64/libvtv*
        - /usr/lib64/liblsan*
        - /usr/lib64/libubsan*
        - /usr/lib64/libcilkrts*
        - /usr/lib64/libmpx*
        - /usr/lib64/crt*.o
    - ^libgcc-32bit :
        - /usr/lib32/libgcc*
        - /usr/lib32/libasan*
        - /usr/lib32/libtsan*
        - /usr/lib32/libatomic*
        - /usr/lib32/libitm*
        - /usr/lib32/libquadmath*
        - /usr/lib32/libssp*
        - /usr/lib32/libmudflap*
        - /usr/lib32/libsanit*
        - /usr/lib32/libvtv*
        - /usr/lib32/liblsan*
        - /usr/lib32/libubsan*
        - /usr/lib32/libcilkrts*
        - /usr/lib32/libmpx*
        - /usr/lib32/crt*.o
    - ^libgfortran : /usr/lib64/*fortran*
    - ^libgfortran-32bit : /usr/lib32/*fortran*
    - ^libgomp : /usr/lib64/libgomp*
    - ^libgomp-32bit : /usr/lib32/libgomp*
    - ^libstdc++ :
        - /usr/lib64/lib*++*
        - /usr/share/locale/*/LC_MESSAGES/cpplib.mo
        - /usr/share/locale/*/LC_MESSAGES/libstdc++.mo
    - ^libstdc++-32bit : /usr/lib32/lib*++*
    - main : /usr/lib64/*.a
    - ^g++ :
        - /usr/bin/c++
        - /usr/bin/cpp
        - /usr/bin/g++*
        - /usr/bin/*-g++*
        - /usr/bin/*-c++*
        - /usr/include/c++
        - /usr/lib64/lib*++*.a
        - /usr/share/man/*/cpp*
        - /usr/share/man/*/g++*
    - ^gfortran :
        - /usr/bin/*fortran*
        - /usr/lib64/*fortran*.a
        - /usr/share/man/*/*fortran*
setup      : |
    %patch -p1 < $pkgfiles/0001-gcc-Ensure-SSP-is-always-present.patch
    %patch -p1 < $pkgfiles/0002-Use-usr-lib-64-32-x32-for-linker-locations-on-Solus-.patch
    %patch -p1 < $pkgfiles/optimize-at-least-some.patch
    %patch -p1 < $pkgfiles/optimize.patch

    # Fix invalid instructions i386
    %patch -p1 < $pkgfiles/bz80706.patch

    %patch -p1 < $pkgfiles/narrow-vpxor.patch

    export triplet=x86_64-solus-linux
    # Set sane and safe flags for a compiler build
    export CFLAGS="-mtune=generic -march=x86-64 -g1 -O3 -fstack-protector -pipe -fPIC -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=0x1000"
    export CXXFLAGS="-mtune=generic -march=x86-64 -g1 -O3 -pipe -fPIC -Wl,-z,max-page-size=0x1000"
    export CFLAGS_FOR_TARGET=${CFLAGS}
    export CC=${triplet}-gcc
    export CXX=${triplet}-g++

    mkdir build; pushd build
    ../configure --prefix=/usr \
               --with-pkgversion='Solus' \
               --libdir=/usr/lib64 \
               --libexecdir=/usr/lib64 \
               --with-system-zlib \
               --enable-shared \
               --enable-threads=posix \
               --enable-gnu-indirect-function \
               --enable-__cxa_atexit \
               --enable-plugin \
               --enable-gold \
               --enable-ld=default \
               --enable-clocale=gnu \
               --enable-multilib \
               --with-multilib-list=m32,m64 \
               --enable-lto \
               --with-bugurl='https://dev.solus-project.com/' \
               --with-arch_32=i686 \
               --enable-linker-build-id  \
               --build=${triplet} \
               --target=${triplet} \
               --enable-languages=c,c++,fortran

    # Print the summary
    ../contrib/test_summary
build      : |
    %make -C build profiledbootstrap
install    : |
    %make_install -C build

    export triplet=x86_64-solus-linux
    # Linky linky
    install -dm 00755 $installdir/lib
    ln -s /usr/bin/cpp $installdir/lib/cpp
    ln -s /usr/bin/gcc $installdir/usr/bin/cc

    for crt in libgcc.a crtbegin.o crtend.o crtbeginS.o crtendS.o; do
        ln -s %libdir%/gcc/$triplet/$version/$crt $installdir/usr/lib64/$crt
        ln -s %libdir%/gcc/$triplet/$version/32/$crt $installdir/usr/lib32/$crt
    done

    # Ensure LTO will work properly.
    install -dm 00755 $installdir/%libdir%/bfd-plugins
    ln -s %libdir%/gcc/$triplet/$version/liblto_plugin.so $installdir/%libdir%/bfd-plugins/liblto_plugin.so

    # eopkg built-in dbginfo is janky
    rm $installdir/usr/bin/gcov-dump
